# Trust local connection - no password required.
local       all             all                         trust
# Only secured remote connection from given IP-Range accepted and password are encoded using MD5
#hostssl    all             all     < Cluster IP-Range >/< Prefix length >         md5
hostssl     all             all     127.0.0.1/32        md5

hostssl     all             all     samenet             md5

hostssl     replication     all     samenet             md5
