listen_addresses = '*'
ssl = on
ssl_cert_file = '/erp/secrets/server.crt'
ssl_key_file = '/erp/secrets/server.key'
wal_level = 'logical'
max_wal_senders=5
max_replication_slots=5
hot_standby=on
log_statement=none