/*
 * (C) Copyright IBM Deutschland GmbH 2021, 2025
 * (C) Copyright IBM Corp. 2021, 2025
 *
 * non-exclusively licensed to gematik GmbH
 */

STATUS(unknown,                            Unknown,                            0)
STATUS(continue_,                          Continue,                         100)
STATUS(switching_protocols,                SwitchingProtocols,               101)
STATUS(processing,                         Processing,                       102)
STATUS(ok,                                 OK,                               200)
STATUS(created,                            Created,                          201)
STATUS(accepted,                           Accepted,                         202)
STATUS(non_authoritative_information,      NonAuthoritativeInformation,      203)
STATUS(no_content,                         NoContent,                        204)
STATUS(reset_content,                      ResetContent,                     205)
STATUS(partial_content,                    PartialContent,                   206)
STATUS(multi_status,                       MultiStatus,                      207)
STATUS(already_reported,                   AlreadyReported,                  208)
STATUS(im_used,                            ImUsed,                           226)
STATUS(multiple_choices,                   MultipleChoices,                  300)
STATUS(moved_permanently,                  MovedPermanently,                 301)
STATUS(found,                              Found,                            302)
STATUS(see_other,                          SeeOther,                         303)
STATUS(not_modified,                       NotModified,                      304)
STATUS(use_proxy,                          UseProxy,                         305)
STATUS(temporary_redirect,                 TemporaryRedirect,                307)
STATUS(permanent_redirect,                 PermanentRedirect,                308)
STATUS(bad_request,                        BadRequest,                       400)
STATUS(unauthorized,                       Unauthorized,                     401)
STATUS(payment_required,                   PaymentRequired,                  402)
STATUS(forbidden,                          Forbidden,                        403)
STATUS(not_found,                          NotFound,                         404)
STATUS(method_not_allowed,                 MethodNotAllowed,                 405)
STATUS(not_acceptable,                     NotAcceptable,                    406)
STATUS(proxy_authentication_required,      ProxyAuthenticationRequired,      407)
STATUS(request_timeout,                    RequestTimeout,                   408)
STATUS(conflict,                           Conflict,                         409)
STATUS(gone,                               Gone,                             410)
STATUS(length_required,                    LengthRequired,                   411)
STATUS(precondition_failed,                PreconditionFailed,               412)
STATUS(payload_too_large,                  PayloadTooLarge,                  413)
STATUS(uri_too_long,                       UriTooLong,                       414)
STATUS(unsupported_media_type,             UnsupportedMediaType,             415)
STATUS(range_not_satisfiable,              RangeNotSatisfiable,              416)
STATUS(expectation_failed,                 ExpectationFailed,                417)
STATUS(misdirected_request,                MisdirectedRequest,               421)
STATUS(unprocessable_entity,               UnprocessableEntity,              422)
STATUS(locked,                             Locked,                           423)
STATUS(failed_dependency,                  FailedDependency,                 424)
STATUS(upgrade_required,                   UpgradeRequired,                  426)
STATUS(precondition_required,              PreconditionRequired,             428)
STATUS(too_many_requests,                  TooManyRequests,                  429)
STATUS(request_header_fields_too_large,    RequestHeaderFieldsTooLarge,      431)
STATUS(connection_closed_without_response, ConnectionCclosedWithoutResponse, 444)
STATUS(unavailable_for_legal_reasons,      UnavailableForLegalReasons,       451)
STATUS(client_closed_request,              ClientClosedRequest,              499)
STATUS(internal_server_error,              InternalServerError,              500)
STATUS(not_implemented,                    NotImplemented,                   501)
STATUS(bad_gateway,                        BadGateway,                       502)
STATUS(service_unavailable,                ServiceUnavailable,               503)
STATUS(gateway_timeout,                    GatewayTimeout,                   504)
STATUS(http_version_not_supported,         HttpVersionNotSupported,          505)
STATUS(variant_also_negotiates,            VariantAlsoNegotiates,            506)
STATUS(insufficient_storage,               InsufficientStorage,              507)
STATUS(loop_detected,                      LoopDetected,                     508)
STATUS(not_extended,                       NotExtended,                      510)
STATUS(network_authentication_required,    NetworkAuthenticationRequired,    511)
STATUS(network_connect_timeout_error,      NetworkConnectTimeoutError,       599)
