#!/bin/bash

#
# (C) Copyright IBM Deutschland GmbH 2021
# (C) Copyright IBM Corp. 2021
#

set -o nounset

if [ "$#" -ne 2 ]; then
    echo
    echo "Usage: $0 [in:path_to_install_manifest.txt] [out:path_to_manifest]"
    echo
    echo "  path_to_install_manifest.txt  Generated by CMake (/build/install_manifest.txt)"
    echo "  path_to_manifest              Output manifest generated with this script (/app/bin/myapp.manifest)"
    echo
    exit 1
fi

INSTALL_MANIFEST=$1
TARGET=$2

if [ ! -f $INSTALL_MANIFEST ]; then
    echo
    echo "File does not exist \"$INSTALL_MANIFEST\"."
    echo
    exit 1
fi

if [ ! -f $TARGET ]; then
    echo
    echo "File does not exist \"$TARGET\"."
    echo
    exit 1
fi

echo "--------------------------------------------"
echo "Create manifest"
echo "--------------------------------------------"

BUF=""
while read line || [ -n "$line" ]; do
    basename=`basename $line`

    # Add 'comma,newline' only when BUF is not empty. This ensures that these chars appear to every row except the initial row.
    # This mechanism is required in order to have a clean substition within the array syntax.
    if [ $BUF ]; then
        BUF+=",\n"
    fi

    if [ $basename = "erp-processing-context" ]; then
        BUF+="\"file:$basename\""
    else
        BUF+="\"file:$line\""
    fi
done < <(cat $INSTALL_MANIFEST)

# Replace the placeholders in the manifest file with the given values.

sed -i "s#__ADDITIONAL_TRUST_FILES__#$BUF#" $TARGET
