#
# (C) Copyright IBM Deutschland GmbH 2021, 2024
# (C) Copyright IBM Corp. 2021, 2024
#
# non-exclusively licensed to gematik GmbH
#

services:
  # --------------------------------------------------------------------------------
  # HSM Simulator
  # --------------------------------------------------------------------------------
  hsm-simulator-1:
    hostname: com.ibm.erp.hsm-simulator
    image: de.icr.io/erp_dev/vau-hsm:latest
    container_name: erp-hsm-simulator-1
    environment:
      SIMULATOR_PORT: 3001
    ports:
      - "9000:3001"

  # --------------------------------------------------------------------------------
  # TPM Server (tpm server port 2321, platform server port 2322)
  # --------------------------------------------------------------------------------
  tpm-server:
    hostname: com.ibm.erp.tpm-server
    image: de.icr.io/erp_dev/tpm-client:latest
    container_name: erp-tpm-server
    ports:
      - "9002:2321"
      - "9003:2322"
    environment:
      TPM_INTERFACE_TYPE: socsim

  # --------------------------------------------------------------------------------
  # Redis server
  # --------------------------------------------------------------------------------
  redis-server:
    hostname: com.ibm.erp.redis-server
    image: de.icr.io/erp_dev/redis:6.0.11
    container_name: erp-redis-server
    ports:
      - "9004:6379"
    volumes:
      - './redis:/data'
      - './tls:/tls'
    command: ["/usr/local/bin/redis-server", "/data/redis.conf", "--port 0", "--tls-port 6379", "--tls-cert-file /tls/server.crt", "--tls-key-file /tls/server.key", "--tls-auth-clients no", "--protected-mode no", "--tls-ca-cert-file /tls/rootCA.crt"]

  # --------------------------------------------------------------------------------
  # Postgres
  # --------------------------------------------------------------------------------
  postgres:
    hostname: postgres-erp
    image: de.icr.io/erp_dev/erp-postgres-db:master
    container_name: erp-postgres
    ports:
      - "9005:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_DB: 'erp_processing_context'
      POSTGRES_USER: 'erp_admin'
      POSTGRES_PASSWORD: 'erp0815'
    volumes:
      - './tls:/tls'
    entrypoint: >
      /bin/bash -c "
      install -o postgres -m 600 /tls/server.key /erp/secrets/server.key &&
      install -o postgres -m 644 /tls/server.crt /erp/secrets/server.crt &&
      docker-entrypoint.sh
      -c ssl=on
      -c ssl_cert_file=/erp/secrets/server.crt
      -c ssl_key_file=/erp/secrets/server.key
      -c wal_level=logical
      -c log_statement=none"
    # set log_statement=all to get detailed output

  # --------------------------------------------------------------------------------
  # Postgres
  # --------------------------------------------------------------------------------
  postgres-erp-medication-exporter:
    hostname: postgres-exporter
    image: de.icr.io/erp_dev/erp-postgres-db:master
    container_name: erp-postgres-medication-exporter
    ports:
      - "9006:5433"
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_DB: 'erp_event_db'
      POSTGRES_USER: 'erp_admin'
      POSTGRES_PASSWORD: 'erp0815'
      PGPORT: '5433'
    volumes:
      - './tls:/tls'
    entrypoint: >
      /bin/bash -c "
      install -o postgres -m 600 /tls/server.key /erp/secrets/server.key &&
      install -o postgres -m 644 /tls/server.crt /erp/secrets/server.crt &&
      docker-entrypoint.sh
      -c ssl=on
      -c ssl_cert_file=/erp/secrets/server.crt
      -c ssl_key_file=/erp/secrets/server.key
      -c wal_level=logical
      -c log_statement=none"
    # set log_statement=all to get detailed output

  # --------------------------------------------------------------------------------
  # Postgres database schema import
  # --------------------------------------------------------------------------------
  db-schema:
    image: postgres:16
    container_name: erp-postgres-schema
    volumes:
      - './tls:/tls'
      - '../scripts:/data'
    depends_on:
      - postgres
      - postgres-erp-medication-exporter
    environment:
      PGPASSWORD: 'erp0815'
      PGSSLROOTCERT: '/tls/rootCA.crt'
    entrypoint: >
      /bin/bash -c "
      while true ;
          do echo 'Waiting for postgresql' ;
          psql -p 5432 -U erp_admin -d erp_processing_context -h postgres-erp -c '\\q' ;
          if [ $? -eq 0 ] ; then
              break ;
          fi ;
          sleep 0.5 ;
      done ;
      while true ;
          do echo 'Waiting for postgresql' ;
          psql -p 5433 -U erp_admin -d erp_event_db -h postgres-exporter -c '\\q' ;
          if [ $? -eq 0 ] ; then
              break ;
          fi ;
          sleep 0.5 ;
      done ;
      /data/reset_database.sh postgres-erp 5432 erp_processing_context erp_admin erp0815 ;
      /data/reset_event_database.sh postgres-exporter 5433 erp_event_db erp_admin erp0815 erp_processing_context postgres-erp 5432 erp_admin erp0815"

  # --------------------------------------------------------------------------------
  # epa-test-mock
  # --------------------------------------------------------------------------------
  epa-test-mock:
    image: de.icr.io/erp_dev/epa-test-mock:v-0.76.0
    container_name: epa-test-mock
    ports:
      - "18888:8888"
    volumes:
      - './tls:/tls'
      - './epa-test-mock:/lzconfig'
