#ifndef ERP_PROCESSING_CONTEXT_SRC_ERP_TSL_TSLERRORCODE_HXX
#define ERP_PROCESSING_CONTEXT_SRC_ERP_TSL_TSLERRORCODE_HXX

enum TslErrorCode
{
    UNKNOWN_ERROR,
    TSL_INIT_ERROR,
    TSL_CERT_EXTRACTION_ERROR,
    MULTIPLE_TRUST_ANCHOR,
    TSL_SIG_CERT_EXTRACTION_ERROR,
    TSL_DOWNLOAD_ADDRESS_ERROR,
    TSL_DOWNLOAD_ERROR,
    TSL_ID_INCORRECT,
    // VALIDITY_WARNING_1 - TSL grace period is currently 0
    VALIDITY_WARNING_2,
    // TSL_NEXTUPDATE_EXPIRED - should not be used according to gemSpec_PKI
    TSL_NOT_WELLFORMED,
    TSL_SCHEMA_NOT_VALID,
    XML_SIGNATURE_ERROR,
    WRONG_KEYUSAGE,
    WRONG_EXTENDEDKEYUSAGE,
    CERT_TYPE_MISMATCH,
    CERT_READ_ERROR,
    CERTIFICATE_NOT_VALID_TIME,
    AUTHORITYKEYID_DIFFERENT,
    CERTIFICATE_NOT_VALID_MATH,
    SERVICESUPPLYPOINT_MISSING,
    CA_CERT_MISSING,
    // OCSP_CHECK_REVOCATION_FAILED - TOLERATE_OCSP_VAILURE is currently always false
    OCSP_CHECK_REVOCATION_ERROR,
    OCSP_CERT_MISSING,
    OCSP_SIGNATURE_ERROR,
    OCSP_NOT_AVAILABLE,
    CERT_TYPE_INFO_MISSING,
    // OCSP_PROXY_NOT_AVAILABLE - should not be used according to gemSpec_PKI
    CA_CERTIFICATE_REVOKED_IN_TSL,
    NO_OCSP_CHECK,
    CERTHASH_EXTENSION_MISSING,
    CERTHASH_MISMATCH,
    TSL_CA_NOT_LOADED,
    CRL_CHECK_ERROR,
    CERT_UNKNOWN,
    CERT_REVOKED,
    QC_STATEMENT_ERROR,
    PROVIDED_OCSP_RESPONSE_NOT_VALID,
    OCSP_NONCE_MISMATCH,
    ATTR_CERT_MISMATCH,
    CRL_DOWNLOAD_ERROR,
    CRL_OUTDATED_ERROR,
    CRL_SIGNER_CERT_MISSING,
    CRL_SIGNATURE_ERROR,
    OCSP_STATUS_ERROR,
    CA_CERTIFICATE_NOT_QES_QUALIFIED,
    VL_UPDATE_ERROR,
    CERT_TYPE_CA_NOT_AUTHORIZED,
    CA_CERTIFICATE_REVOKED_IN_BNETZA_VL,

    // the following warning is not part of specification and is intended to notify
    // about planned update of TI-Trust-Anchor
    TSL_CA_UPDATE_WARNING
};

#endif
