#
# (C) Copyright IBM Deutschland GmbH 2021, 2025
# (C) Copyright IBM Corp. 2021, 2025
#
# non-exclusively licensed to gematik GmbH
#

apiVersion: v1
kind: Service
metadata:
  labels:
    app: erp-processing-context-1
  name: erp-processing-context-1
  namespace: %NAMESPACE%
spec:
  ports:
    - name: http
      port: 9085
      protocol: TCP
      targetPort: 9085
    - name: enrolment
      port: 9191
      protocol: TCP
      targetPort: 9191
    - name: admin
      port: 9999
      protocol: TCP
      targetPort: 9999      
  selector:
    app: erp-processing-context-1
  type: ClusterIP
