#
# (C) Copyright IBM Deutschland GmbH 2021, 2024
# (C) Copyright IBM Corp. 2021, 2024
#
# non-exclusively licensed to gematik GmbH
#

apiVersion: v1
kind: Service
metadata:
  labels:
    app: erp-medication-exporter
  name: erp-medication-exporter
  namespace: %NAMESPACE%
spec:
  ports:
    - name: http
      port: 9087
      protocol: TCP
      targetPort: 9087
    - name: enrolment
      port: 9191
      protocol: TCP
      targetPort: 9191
    - name: admin
      port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: erp-medication-exporter
  type: ClusterIP
