/*
 * (C) Copyright IBM Deutschland GmbH 2021, 2026
 * (C) Copyright IBM Corp. 2021, 2026
 *
 * non-exclusively licensed to gematik GmbH
 */

#pragma once
#include "PushNotificationDevice.hxx"
#include "fhirtools/model/NumberAsStringParserDocument.hxx"
#include "shared/util/SafeString.hxx"

namespace model
{
class PushNotification;
class PushNotificationDevice;

enum class PushNotificationPrio
{
    high,
    low
};

// https://gematik.github.io/gem-push-notifications-concept/1.1/#push_gateway_openapi.html
class EncryptedNotification
{
public:
    EncryptedNotification(std::string ciphertext, std::string timeMessageEncrypted, std::string keyIdentifier,
                          std::string identifier, PushNotificationDevice device);

    void setPrio(PushNotificationPrio prio);

    void toJson(rapidjson::Value& parent, rapidjson::Document::AllocatorType& alloc) const;

private:
    // Base64 encoded ciphertext. The original ciphertext always contains 1024 bytes of payload. Encoding this along
    // with the IV and Authentication code using Base64 results in 1404 bytes for this data field.
    // required
    std::string mCiphertext;

    // Year + Month the key was derived and the message was sent. e.g. 2024-11 for November 2024.
    // required
    std::string mTimeMessageEncrypted;

    // A string containing an identifier for the key. This is used to identify the key and the corresponding service
    // (Fachdienst) when a push notification is received within the FdV. The key_identifier is generated by the FdV,
    // must be random and must not be reused for a different ISS. An UUID is recommended.
    // required
    std::string mKeyIdentifier;

    // An identifier to reidentify the push notification at the originating fachdienst. This property may be send to a
    // 3rd service (e.g. in combination with some properties from the data dictionary) to create a complete list of all
    // push notifications that have been sent to a client. This Property is optional. If the Fachdienst generated a
    // history item for the push notificiation it should send the identifier of the history item using this field.
    // NOTE: It is possible that this identifier is not unique across multiple push notifications, e.g. if the
    // fachdienst sends multiple push notifications for the same event (e.g. in a retry scenario or multiple push
    // notifications being sent for one event).
    // optional
    // A_28135-01: must be filled with either Audit-Event-Id or Communication-Id
    std::string mIdentifier;

    // The priority of the notification. If omitted, high is assumed. This may be used by push gateways to deliver less
    // time-sensitive notifications in a way that will preserve battery power on mobile devices.
    // optional
    PushNotificationPrio mPrio{PushNotificationPrio::low};

    // This is a dictionary of the current number of unacknowledged communications for the recipient user. Counts whose
    // value is zero should be omitted.
    // optional
    // PushNotificationCounts mCounts;

    // The device that the notification should be sent to.
    // required
    PushNotificationDevice mDevice;
};

std::string
serializePushNotifications(const std::vector<std::pair<std::string, EncryptedNotification>>& pushNotifications);

}// model
