port: 8888
keyfilename: "../tisim-pki/epa-as-1-mock.epa.telematik-test.p12"
keypin: "00"
vauServerKeys: "../tisim-pki/vau_server_keys.cbor"
vauSigKey: "../tisim-pki/epa-vau-aut-key.p8"
vauSigCert: "../tisim-pki/epa-vau-aut.der"
isProduction: false
mockOcsp: true
mockOcspTlsResponderCert: "../tisim-pki/ecc/gem-rca/fd4/ocsp-fd.pem"
mockOcspTlsResponderKey: "../tisim-pki/ecc/gem-rca/fd4/ocsp-fd.pkcs8"
mockOcspVauResponderCert: "../tisim-pki/ecc/gem-rca/fd1/ocsp-fd.pem"
mockOcspVauResponderKey: "../tisim-pki/ecc/gem-rca/fd1/ocsp-fd.pkcs8"
ocspResponseVauSig: "../tisim-pki/ocsp-response-vau-sig.der"
ocspResponseValidForMinutes: 720
ocspURI: "https://erp.box2.erezepttest.net/ocspf"
vauCert: "../tisim-pki/epa-vau-aut.der"
vauCA: "../tisim-pki/ACLOS.FD-CA1.der"
templatePath: "../lzconfig/templates"
ocspResponseServerTLS: "../tisim-pki/ocsp-response-tls-epa-as-mock.der"
ocspResponseServerTLSValidForMinutes: 50
ocspResponseServerTLSOmit: false
mode: default
chaosRatio: 50